/**
 * Export utilities for the Resume Optimization Flow
 *
 * Generates downloadable content in Markdown format for:
 * - Rewritten resume content
 * - Interview Q&A study guide
 * - ATS scan report
 */

import type {
  EditedContent,
  RewrittenExperience,
  InterviewPrepResult,
  InterviewQuestion,
  ATSScanResult,
  ATSSectionResult,
  AnalysisResult,
} from "@/lib/types/optimize-flow"

// ============================================
// Resume Export (Phase 6A)
// ============================================

export interface ResumeExportOptions {
  jobTitle: string
  companyName?: string
  includeOriginalBullets?: boolean
  includeKeywordsAdded?: boolean
}

/**
 * Generate markdown content for the rewritten resume
 */
export function generateResumeMarkdown(
  content: EditedContent,
  options: ResumeExportOptions
): string {
  const { jobTitle, companyName, includeOriginalBullets = false, includeKeywordsAdded = true } = options
  const lines: string[] = []

  // Header
  lines.push("# Optimized Resume Content")
  lines.push("")
  lines.push(`**Target Position:** ${jobTitle}${companyName ? ` at ${companyName}` : ""}`)
  lines.push(`**Generated:** ${new Date().toLocaleDateString()}`)
  lines.push("")
  lines.push("---")
  lines.push("")

  // Professional Summary
  lines.push("## Professional Summary")
  lines.push("")
  lines.push(content.professionalSummary)
  lines.push("")

  // Work Experience
  lines.push("## Work Experience")
  lines.push("")

  for (const exp of content.workExperiences) {
    lines.push(`### ${exp.title}`)
    lines.push(`**${exp.company}** | ${exp.duration}`)
    lines.push("")

    // Rewritten bullets
    for (const bullet of exp.rewrittenBullets) {
      lines.push(`- ${bullet}`)
    }
    lines.push("")

    // Original bullets (optional)
    if (includeOriginalBullets && exp.originalBullets.length > 0) {
      lines.push("<details>")
      lines.push("<summary>Original bullets (for reference)</summary>")
      lines.push("")
      for (const bullet of exp.originalBullets) {
        lines.push(`- ${bullet}`)
      }
      lines.push("")
      lines.push("</details>")
      lines.push("")
    }

    // Keywords added (optional)
    if (includeKeywordsAdded && exp.keywordsAdded.length > 0) {
      lines.push(`*Keywords added: ${exp.keywordsAdded.join(", ")}*`)
      lines.push("")
    }
  }

  // Footer
  lines.push("---")
  lines.push("")
  lines.push("*Generated by Resume Optimization Flow*")

  return lines.join("\n")
}

/**
 * Generate plain text resume content (for easy copying)
 */
export function generateResumePlainText(content: EditedContent): string {
  const lines: string[] = []

  // Professional Summary
  lines.push("PROFESSIONAL SUMMARY")
  lines.push("")
  lines.push(content.professionalSummary)
  lines.push("")
  lines.push("")

  // Work Experience
  lines.push("WORK EXPERIENCE")
  lines.push("")

  for (const exp of content.workExperiences) {
    lines.push(`${exp.title}`)
    lines.push(`${exp.company} | ${exp.duration}`)
    lines.push("")

    for (const bullet of exp.rewrittenBullets) {
      lines.push(`• ${bullet}`)
    }
    lines.push("")
  }

  return lines.join("\n")
}

// ============================================
// Interview Q&A Export (Phase 6B)
// ============================================

export interface InterviewExportOptions {
  jobTitle: string
  companyName?: string
  includeKeyPoints?: boolean
  includeRelatedExperience?: boolean
}

/**
 * Generate markdown content for interview preparation study guide
 */
export function generateInterviewMarkdown(
  result: InterviewPrepResult,
  options: InterviewExportOptions
): string {
  const { jobTitle, companyName, includeKeyPoints = true, includeRelatedExperience = true } = options
  const lines: string[] = []

  // Header
  lines.push("# Interview Preparation Guide")
  lines.push("")
  lines.push(`**Position:** ${jobTitle}${companyName ? ` at ${companyName}` : ""}`)
  lines.push(`**Prepared:** ${new Date().toLocaleDateString()}`)
  lines.push("")
  lines.push("---")
  lines.push("")

  // Introduction
  lines.push("## How to Use This Guide")
  lines.push("")
  lines.push("1. **Practice out loud** - Don't just read the answers, speak them")
  lines.push("2. **Customize** - Adapt the answers to your personal style")
  lines.push("3. **Time yourself** - Keep answers to 2-3 minutes max")
  lines.push("4. **Use STAR format** - Situation, Task, Action, Result")
  lines.push("")
  lines.push("---")
  lines.push("")

  // Questions
  lines.push("## Interview Questions")
  lines.push("")

  result.questions.forEach((q, index) => {
    lines.push(`### Question ${index + 1}: ${q.category}`)
    lines.push("")
    lines.push(`**Difficulty:** ${formatDifficulty(q.difficulty)}`)
    lines.push("")
    lines.push(`> ${q.question}`)
    lines.push("")

    // Answer
    lines.push("#### Perfect Answer")
    lines.push("")
    lines.push(q.perfectAnswer)
    lines.push("")

    // Key Points
    if (includeKeyPoints && q.keyPoints.length > 0) {
      lines.push("#### Key Points to Hit")
      lines.push("")
      for (const point of q.keyPoints) {
        lines.push(`- ✓ ${point}`)
      }
      lines.push("")
    }

    // Related Experience
    if (includeRelatedExperience && q.relatedExperience) {
      lines.push("#### Based on Your Experience")
      lines.push("")
      lines.push(`*${q.relatedExperience}*`)
      lines.push("")
    }

    lines.push("---")
    lines.push("")
  })

  // Tips Section
  lines.push("## General Interview Tips")
  lines.push("")
  lines.push("- **Research the company** - Know their products, culture, and recent news")
  lines.push("- **Prepare questions** - Have 3-5 thoughtful questions ready")
  lines.push("- **Follow up** - Send a thank-you email within 24 hours")
  lines.push("- **Be specific** - Use concrete examples with numbers when possible")
  lines.push("")
  lines.push("---")
  lines.push("")
  lines.push("*Generated by Resume Optimization Flow*")

  return lines.join("\n")
}

function formatDifficulty(difficulty: InterviewQuestion["difficulty"]): string {
  switch (difficulty) {
    case "hard":
      return "⭐⭐⭐ Hard"
    case "very_hard":
      return "⭐⭐⭐⭐ Very Hard"
    case "expert":
      return "⭐⭐⭐⭐⭐ Expert"
  }
}

// ============================================
// ATS Report Export (Phase 6C)
// ============================================

export interface ATSReportExportOptions {
  jobTitle: string
  companyName?: string
  analysisResult?: AnalysisResult
}

/**
 * Generate markdown content for ATS scan report
 */
export function generateATSReportMarkdown(
  result: ATSScanResult,
  options: ATSReportExportOptions
): string {
  const { jobTitle, companyName, analysisResult } = options
  const lines: string[] = []

  // Header
  lines.push("# ATS Compatibility Report")
  lines.push("")
  lines.push(`**Position:** ${jobTitle}${companyName ? ` at ${companyName}` : ""}`)
  lines.push(`**Scanned:** ${new Date().toLocaleDateString()}`)
  lines.push("")
  lines.push("---")
  lines.push("")

  // Overall Score
  lines.push("## Overall Score")
  lines.push("")
  lines.push(`# ${result.overallScore}/100`)
  lines.push("")
  lines.push(getScoreDescription(result.overallScore))
  lines.push("")

  // Include match score if available
  if (analysisResult) {
    lines.push(`**Job Match Score:** ${analysisResult.matchScore}/100`)
    lines.push("")
  }

  lines.push("---")
  lines.push("")

  // Critical Issues
  if (result.criticalIssues.length > 0) {
    lines.push("## 🚨 Critical Issues")
    lines.push("")
    lines.push("These issues need immediate attention:")
    lines.push("")

    for (const issue of result.criticalIssues) {
      lines.push(`### ${issue.section}`)
      lines.push("")
      lines.push(`**Problem:** ${issue.issue}`)
      lines.push("")
      lines.push(`**Fix:** ${issue.fix}`)
      lines.push("")
    }

    lines.push("---")
    lines.push("")
  }

  // Warnings
  if (result.warnings.length > 0) {
    lines.push("## ⚠️ Warnings")
    lines.push("")
    lines.push("These issues may affect ATS parsing:")
    lines.push("")

    for (const warning of result.warnings) {
      lines.push(`- **${warning.section}:** ${warning.issue}`)
      lines.push(`  - *Fix:* ${warning.fix}`)
    }
    lines.push("")

    lines.push("---")
    lines.push("")
  }

  // Section-by-Section Analysis
  lines.push("## Section Analysis")
  lines.push("")
  lines.push("| Section | Status | Details |")
  lines.push("|---------|--------|---------|")

  for (const section of result.sections) {
    const statusIcon = getStatusIcon(section.status)
    lines.push(`| ${section.name} | ${statusIcon} ${section.status.toUpperCase()} | ${section.details} |`)
  }
  lines.push("")

  // Sections with issues (expanded)
  const sectionsWithIssues = result.sections.filter((s) => s.status !== "pass")
  if (sectionsWithIssues.length > 0) {
    lines.push("### Section Details")
    lines.push("")

    for (const section of sectionsWithIssues) {
      lines.push(`#### ${section.name}`)
      lines.push("")
      if (section.risk) {
        lines.push(`**Risk:** ${section.risk}`)
        lines.push("")
      }
      if (section.fix) {
        lines.push(`**How to Fix:** ${section.fix}`)
        lines.push("")
      }
    }

    lines.push("---")
    lines.push("")
  }

  // Recommendations
  if (result.recommendations.length > 0) {
    lines.push("## 💡 Recommendations")
    lines.push("")

    for (let i = 0; i < result.recommendations.length; i++) {
      lines.push(`${i + 1}. ${result.recommendations[i]}`)
    }
    lines.push("")

    lines.push("---")
    lines.push("")
  }

  // Footer
  lines.push("## What is ATS?")
  lines.push("")
  lines.push("Applicant Tracking Systems (ATS) are software used by 99% of Fortune 500 companies")
  lines.push("to filter resumes before human review. A high ATS compatibility score means your")
  lines.push("resume is more likely to be seen by recruiters.")
  lines.push("")
  lines.push("---")
  lines.push("")
  lines.push("*Generated by Resume Optimization Flow*")

  return lines.join("\n")
}

function getScoreDescription(score: number): string {
  if (score >= 90) return "✅ **Excellent** - Your resume is highly ATS-compatible"
  if (score >= 80) return "✅ **Good** - Minor improvements recommended"
  if (score >= 70) return "⚠️ **Fair** - Some issues need attention"
  if (score >= 60) return "⚠️ **Needs Work** - Multiple issues detected"
  return "🚨 **Poor** - Significant changes required"
}

function getStatusIcon(status: ATSSectionResult["status"]): string {
  switch (status) {
    case "pass":
      return "✅"
    case "warning":
      return "⚠️"
    case "fail":
      return "❌"
  }
}

// ============================================
// Download Helpers
// ============================================

/**
 * Trigger a file download in the browser
 */
export function downloadAsFile(content: string, filename: string, mimeType: string = "text/markdown"): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement("a")
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Copy content to clipboard
 */
export async function copyToClipboard(content: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(content)
    return true
  } catch (error) {
    console.error("Failed to copy to clipboard:", error)
    return false
  }
}

/**
 * Generate a safe filename from job title
 */
export function generateFilename(prefix: string, jobTitle: string, extension: string = "md"): string {
  const safeTitle = jobTitle
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 30)

  const date = new Date().toISOString().split("T")[0]
  return `${prefix}-${safeTitle}-${date}.${extension}`
}
