version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: resumate-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333" # REST / gRPC over HTTP
      - "6334:6334" # gRPC
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: